# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pulumigo < Formula
  desc "pulumiGo CLI tool"
  homepage "https://github.com/vincent119/pulumiGo"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.0/pulumiGo_Darwin_x86_64.tar.gz"
      sha256 "1dacde8cfeef65b1ec94b118ddd6b885e0dfaf6521764a9bfd8b81faa49246a8"

      define_method(:install) do
        bin.install "pulumiGo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.0/pulumiGo_Darwin_arm64.tar.gz"
      sha256 "a48664f851d1a4b437878d530cc0752ccb8d015973ece4a587f29ebbe8064f57"

      define_method(:install) do
        bin.install "pulumiGo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.0/pulumiGo_Linux_x86_64.tar.gz"
      sha256 "48bbf3caa615f5c615f0ab39123ad4ed2022632a183468a12f19592f4260ae6f"
      define_method(:install) do
        bin.install "pulumiGo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.0/pulumiGo_Linux_arm64.tar.gz"
      sha256 "eb56639f7c0bbc0c7a0e636c0700d54087a8ef0eb34277cddf6636f766524d7a"
      define_method(:install) do
        bin.install "pulumiGo"
      end
    end
  end

  test do
    system "#{bin}/pulumiGo", "--version"
  end
end
