# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pulumigo < Formula
  desc "pulumiGo CLI tool"
  homepage "https://github.com/vincent119/pulumiGo"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.1/pulumiGo_Darwin_x86_64.tar.gz"
      sha256 "c4ce7f82c73c77d6bebd658e638ea8e052c48ba1dcb3084a3fddfb3256e180a4"

      define_method(:install) do
        bin.install "pulumiGo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.1/pulumiGo_Darwin_arm64.tar.gz"
      sha256 "9ac78fb9f8670dcb0fed2888520296eb462a90c6a4e8af510aba0d3ccd8dac0f"

      define_method(:install) do
        bin.install "pulumiGo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.1/pulumiGo_Linux_x86_64.tar.gz"
      sha256 "7d4bc585d4daa5df191d47a2f1514e0938762c1017f9da0cbec5d95c470a5ef5"
      define_method(:install) do
        bin.install "pulumiGo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.1/pulumiGo_Linux_arm64.tar.gz"
      sha256 "b0e87c5bb85240c70566ed68d8bf1cd4c3f661ad735cc20c86d8b6c06760bcfa"
      define_method(:install) do
        bin.install "pulumiGo"
      end
    end
  end

  test do
    system "#{bin}/pulumiGo", "--version"
  end
end
