# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timesamp < Formula
  desc "A timestamp utility CLI."
  homepage "https://github.com/vincent119/timesamp"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vincent119/timesamp/releases/download/0.0.5/timesamp_Darwin_x86_64.tar.gz"
      sha256 "69e5689c0ed229c04672c661705b563771290a5e8b10eeba342c54e32031f6b2"

      define_method(:install) do
        bin.install "timesamp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vincent119/timesamp/releases/download/0.0.5/timesamp_Darwin_arm64.tar.gz"
      sha256 "ca8f4c9df1ea15eb9f70e21e4134a1a9b5c5448b6b23a17a4684f3cd7f891d4b"

      define_method(:install) do
        bin.install "timesamp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/timesamp/releases/download/0.0.5/timesamp_Linux_x86_64.tar.gz"
      sha256 "5faad9a953fe43987e39e7ddeeb1c53e21f60bffbf77e249a02f415eb3c1d746"
      define_method(:install) do
        bin.install "timesamp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/timesamp/releases/download/0.0.5/timesamp_Linux_arm64.tar.gz"
      sha256 "02b7f3bd7d90f4145614d3d1e6d595c8e9f8f9623cbb2bb83177b632256d72c0"
      define_method(:install) do
        bin.install "timesamp"
      end
    end
  end
end
