# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsregionchange" do
  name "awsregionchange"
  desc "Interactive AWS Profile and Region switcher with TUI"
  homepage "https://github.com/vincent119/awsRegionChange"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awsRegionChange"

  on_macos do
    on_intel do
      url "https://github.com/vincent119/awsRegionChange/releases/download/v#{version}/awsRegionChange_Darwin_x86_64.tar.gz"
      sha256 "4a8e70b9bbb219edf78604ec197addc68833b107c7d95c206561857b2de613c5"
    end
    on_arm do
      url "https://github.com/vincent119/awsRegionChange/releases/download/v#{version}/awsRegionChange_Darwin_arm64.tar.gz"
      sha256 "6fb2f90fdc670f37462260a5e91875cdda7a5c599f4db7b5e4110e007f530120"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vincent119/awsRegionChange/releases/download/v#{version}/awsRegionChange_Linux_x86_64.tar.gz"
      sha256 "4eccdc727a0a5e596ba0018140e385e389de99a58580299ec56a145da9038057"
    end
    on_arm do
      url "https://github.com/vincent119/awsRegionChange/releases/download/v#{version}/awsRegionChange_Linux_arm64.tar.gz"
      sha256 "d35527a82f3783553e19df01bdc897e7fbc5fc1d94611ce848c8fb7da1234ab8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsRegionChange"]
    end
  end

  # No zap stanza required
end
