# This file was generated by GoReleaser. DO NOT EDIT.
cask "pulumigo" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "d43e80379828b668e479df37dcf9e4e54f3bb8b478e85dc0714da065298ea441"
      url "https://github.com/vincent119/pulumiGo/releases/download/v#{version}/pulumiGo_Darwin_x86_64.tar.gz",
        verified: "github.com/vincent119/pulumiGo"
    end
    on_arm do
      sha256 "dea7223a17f77825cd58ca006c01f665b287ed3c6e19dd72944f0a7473290dba"
      url "https://github.com/vincent119/pulumiGo/releases/download/v#{version}/pulumiGo_Darwin_arm64.tar.gz",
        verified: "github.com/vincent119/pulumiGo"
    end
  end

  on_linux do
    on_intel do
      sha256 "5cfe31f17b182495fca75a3c71439b620e0587dc0b79f07cf7b29a6adbc28d4c"
      url "https://github.com/vincent119/pulumiGo/releases/download/v#{version}/pulumiGo_Linux_x86_64.tar.gz",
        verified: "github.com/vincent119/pulumiGo"
    end
    on_arm do
      sha256 "7881c7cef70b347479f6179afa642998e50e5af86e2e48a163ada2c413c34fe0"
      url "https://github.com/vincent119/pulumiGo/releases/download/v#{version}/pulumiGo_Linux_arm64.tar.gz",
        verified: "github.com/vincent119/pulumiGo"
    end
  end

  name "pulumigo"
  desc "pulumiGo CLI tool"
  homepage "https://github.com/vincent119/pulumiGo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pulumigo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pulumiGo"]
    end
  end

  # No zap stanza required

end
