# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsregionchange < Formula
  desc "Interactive AWS Profile and Region switcher with TUI"
  homepage "https://github.com/vincent119/awsRegionChange"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vincent119/awsRegionChange/releases/download/v0.1.0/awsRegionChange_Darwin_x86_64.tar.gz"
      sha256 "a15431a8c00f27c5c2862d12c5898859f7fc360df4e8974ffbaf3154ab49d11d"

      define_method(:install) do
        bin.install "awsRegionChange"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vincent119/awsRegionChange/releases/download/v0.1.0/awsRegionChange_Darwin_arm64.tar.gz"
      sha256 "a91e74e397f5725908089b8605db1053125d779c5ae9ee5beb5824952797bbf8"

      define_method(:install) do
        bin.install "awsRegionChange"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/awsRegionChange/releases/download/v0.1.0/awsRegionChange_Linux_x86_64.tar.gz"
      sha256 "9299435d90a90a1841e5fa4fc6be71f0079d64ff02cc7e780ab180933cd78564"
      define_method(:install) do
        bin.install "awsRegionChange"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/awsRegionChange/releases/download/v0.1.0/awsRegionChange_Linux_arm64.tar.gz"
      sha256 "c9f06363aec50370b51430ca58efdd3bef6163c0f6ec03b962ff1d2f87b07b15"
      define_method(:install) do
        bin.install "awsRegionChange"
      end
    end
  end

  test do
    system "#{bin}/awsRegionChange", "--version"
  end
end
