# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Base64cli < Formula
  desc "An intelligent Base64 encoding/decoding CLI tool with automatic detection."
  homepage "https://github.com/vincent119/base64cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vincent119/base64cli/releases/download/v1.0.0/base64cli_Darwin_x86_64.tar.gz"
      sha256 "f79b0a1f7e4f5b1b60484df4953e914a1e7e1399fff5328b2af16c2156fb21b3"

      define_method(:install) do
        bin.install "base64cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vincent119/base64cli/releases/download/v1.0.0/base64cli_Darwin_arm64.tar.gz"
      sha256 "e51f992e6cb3d79b6410a4a6c77caecf4008a3049f8f0d7dc42b9b7ca181f059"

      define_method(:install) do
        bin.install "base64cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/base64cli/releases/download/v1.0.0/base64cli_Linux_x86_64.tar.gz"
      sha256 "739c3a0b9394805f18fe4cdf7796738ca64c3c34d58d5b85f51a809b711c00f1"
      define_method(:install) do
        bin.install "base64cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/base64cli/releases/download/v1.0.0/base64cli_Linux_arm64.tar.gz"
      sha256 "e7dcab57ac2c3e0b4c9854bdd371493910c97728f26284e14bd81bae6d75d688"
      define_method(:install) do
        bin.install "base64cli"
      end
    end
  end
end
