# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pulumigo < Formula
  desc "Wrapper for Pulumi with stack management helpers"
  homepage "https://github.com/vincent119/pulumiGo"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.5/pulumiGo_Darwin_x86_64.tar.gz"
      sha256 "306d246d1fcb1faedce2add55917699f99c195b7ae687b8861752dd8d2b4e49b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.5/pulumiGo_Darwin_arm64.tar.gz"
      sha256 "b3dee4e47daac8ad1a71d8244d7bc7b3c03054b956c0de54cb900388d27307dd"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.5/pulumiGo_Linux_x86_64.tar.gz"
      sha256 "999e93fee288993343ea04515cb5bfef9928f1fcf5f81ed18b6ef3fb946ab3a0"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/pulumiGo/releases/download/v0.1.5/pulumiGo_Linux_arm64.tar.gz"
      sha256 "61a541bacffb804335c0522a531ef2631419ff2d69cac62d3b8259f48644fe75"
    end
  end

  def install
    bin.install "pulumiGo" => "pulumigo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pulumigo --help")
  end
end
