# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timesamp < Formula
  desc "A timestamp utility CLI."
  homepage "https://github.com/vincent119/timesamp"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vincent119/timesamp/releases/download/0.0.6/timesamp_Darwin_x86_64.tar.gz"
      sha256 "c06d42320281e50e1a8d206d532b715f4d57fe38f6046043208813c16ecd19f2"

      define_method(:install) do
        bin.install "timesamp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vincent119/timesamp/releases/download/0.0.6/timesamp_Darwin_arm64.tar.gz"
      sha256 "587be80d7fc2f6412094fdbd41b694830c3d569b5bc35a9d5a446cab9f4edeba"

      define_method(:install) do
        bin.install "timesamp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/timesamp/releases/download/0.0.6/timesamp_Linux_x86_64.tar.gz"
      sha256 "1b1ebc618d641ce4c9af5dec5cb028a8f8a6b00d72e99b375b25441bb311962b"
      define_method(:install) do
        bin.install "timesamp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincent119/timesamp/releases/download/0.0.6/timesamp_Linux_arm64.tar.gz"
      sha256 "75b75d83bfe60aa4dea6a9271ce10b14c6f68777d9c7c05ef9f8cc9b0bab5ac4"
      define_method(:install) do
        bin.install "timesamp"
      end
    end
  end
end
